In [1]:
import pandas as pd
from datetime import datetime
import numpy as np

#데이터 전처리

In [2]:
subway2023 = pd.read_csv("/content/서울교통공사_역별 시간대별 승하차인원(23.1~23.12) (1).csv", encoding='cp949')
subway2024 = pd.read_csv("/content/서울교통공사_역별 시간대별 승하차인원(24.1~24.12).csv", encoding='cp949')

In [3]:
subway2022 = pd.read_csv("/content/서울교통공사_역별 일별 시간대별 승하차인원 정보_20221231 (1).csv", encoding='cp949')

/tmp/ipykernel_4662/2657294918.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  subway2022 = pd.read_csv("/content/서울교통공사_역별 일별 시간대별 승하차인원 정보_20221231 (1).csv", encoding='cp949')

##2022년 데이터 확인

In [4]:
subway2022.head()

,연번,수송일자,호선,고유역번호(외부역코드),역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,1,2022-01-01,1,150,서울역,승차,120,137,211,439,...,1566,1686,1591,1358,1062,899,1327,814,234,NaN
1,2,2022-01-01,1,150,서울역,하차,113,560,617,910,...,1329,1251,1126,884,764,654,728,416,131,NaN
2,3,2022-01-01,1,151,시청,승차,38,66,101,139,...,474,550,672,528,420,434,491,232,38,NaN
3,4,2022-01-01,1,151,시청,하차,31,195,224,380,...,408,377,354,213,131,98,137,61,24,NaN
4,5,2022-01-01,1,152,종각,승차,44,71,86,158,...,889,964,1024,803,855,1099,1209,255,62,NaN

In [5]:
subway2022 = subway2022.rename(columns={
    '고유역번호(외부역코드)': '역번호'
})

In [6]:
subway2022[subway2022["역번호"].astype(str).str.strip() == ""]

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
132480,132481,2022-08-31,7,,광명사거리,승차,801,1299,3405,3901,...,965,1181,1376,1283,779,521,448,346,124,15.0

In [7]:
subway2022[(subway2022['역명'] == '광명사거리')]

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
502,503,2022-01-01,7,2750,광명사거리,승차,208,208,315,417,...,852,866,710,589,359,408,415,176,58,NaN
503,504,2022-01-01,7,2750,광명사거리,하차,50,122,179,258,...,822,771,771,742,509,456,678,556,235,NaN
1046,1047,2022-01-02,7,2750,광명사거리,승차,191,230,318,566,...,869,900,913,558,468,433,361,156,44,NaN
1047,1048,2022-01-02,7,2750,광명사거리,하차,39,110,173,252,...,773,792,802,772,641,571,811,547,207,NaN
1590,1591,2022-01-03,7,2750,광명사거리,승차,729,1258,3524,3897,...,832,970,1151,1096,616,499,366,184,59,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197949,197950,2022-12-29,7,2750,광명사거리,하차,216,423,669,991,...,1264,1570,1978,2844,2252,1259,1058,1023,713,248.0
198494,198495,2022-12-30,7,2750,광명사거리,승차,702,1026,2595,3069,...,1316,1562,1565,1405,988,600,494,405,194,30.0
198495,198496,2022-12-30,7,2750,광명사거리,하차,197,428,603,1001,...,1739,1884,2289,2388,1698,1026,977,735,699,277.0
199038,199039,2022-12-31,7,2750,광명사거리,승차,407,422,622,823,...,1293,1378,1292,977,878,579,501,426,155,35.0
199039,199040,2022-12-31,7,2750,광명사거리,하차,108,246,309,489,...,1223,1303,1303,1147,883,709,705,669,405,110.0

In [8]:
subway2022[subway2022['역명'] == '광명사거리']['역번호'].unique()

array([2750, '2750', ' '], dtype=object)

In [9]:
np.where(subway2022['연번'] == 	132481)

(array([132480]),)

In [10]:
subway2022.at[132480, '역번호'] = 2750

In [11]:
subway2022['역번호'] = pd.to_numeric(subway2022['역번호'])

In [12]:
subway2022[subway2022['역명'] == '광명사거리']['역번호'].unique()

array([2750])

In [13]:
subway2022[subway2022["역번호"].astype(str).str.strip() == ""]

Empty DataFrame
Columns: [연번, 수송일자, 호선, 역번호, 역명, 승하차구분, 06시이전, 06-07시간대, 07-08시간대, 08-09시간대, 09-10시간대, 10-11시간대, 11-12시간대, 12-13시간대, 13-14시간대, 14-15시간대, 15-16시간대, 16-17시간대, 17-18시간대, 18-19시간대, 19-20시간대, 20-21시간대, 21-22시간대, 22-23시간대, 23-24시간대, 24시이후]
Index: []

[0 rows x 26 columns]

2022년 5월 31일까지 24시간 이후의 데이터가 null로 되어 있으므로 2022년 6월 데이터부터 활용 예정

In [14]:
subway2022.isnull().sum()

연번              0
수송일자            0
호선              0
역번호             0
역명              0
승하차구분           0
06시이전           0
06-07시간대        0
07-08시간대        0
08-09시간대        0
09-10시간대        0
10-11시간대        0
11-12시간대        0
12-13시간대        0
13-14시간대        0
14-15시간대        0
15-16시간대        0
16-17시간대        0
17-18시간대        0
18-19시간대        0
19-20시간대        0
20-21시간대        0
21-22시간대        0
22-23시간대        0
23-24시간대        0
24시이후       82346
dtype: int64

##2023년 데이터 확인

In [15]:
subway2023.head()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,1,2023-01-01,1호선,150,서울역,승차,215,145,231,594,...,2655,2509,2696,2549,2462,2177,2190,1808,734,7
1,2,2023-01-01,1호선,150,서울역,하차,154,636,595,939,...,2282,2295,2526,1930,1897,1487,991,609,280,46
2,3,2023-01-01,1호선,151,시청,승차,48,73,106,194,...,843,895,959,985,670,630,515,330,146,0
3,4,2023-01-01,1호선,151,시청,하차,64,247,293,463,...,602,575,533,456,285,267,246,154,79,18
4,5,2023-01-01,1호선,152,종각,승차,407,235,158,201,...,1145,1402,1223,1272,911,913,906,602,232,3

In [16]:
subway2023.isnull().sum()

연번          0
수송일자        0
호선          0
역번호         0
역명          0
승하차구분       0
06시이전       0
06-07시간대    0
07-08시간대    0
08-09시간대    0
09-10시간대    0
10-11시간대    0
11-12시간대    0
12-13시간대    0
13-14시간대    0
14-15시간대    0
15-16시간대    0
16-17시간대    0
17-18시간대    0
18-19시간대    0
19-20시간대    0
20-21시간대    0
21-22시간대    0
22-23시간대    0
23-24시간대    0
24시이후       0
dtype: int64

##2024년 데이터 확인

In [17]:
subway2024.head()

,연번,날짜,호선,역번호,역명,구분,06시 이전,06시-07시,07시-08시,08시-09시,...,15시-16시,16시-17시,17시-18시,18시-19시,19시-20시,20시-21시,21시-22시,22시-23시,23시-24시,24시 이후
0,1,2024-01-01,1호선,150,서울역,승차,383,257,308,975,...,2716,2882,2871,2685,2922,2031,2279,1729,868,43
1,2,2024-01-01,1호선,150,서울역,하차,249,867,834,1201,...,2615,2501,2829,2095,1833,1465,1031,585,298,82
2,3,2024-01-01,1호선,151,시청,승차,188,92,167,245,...,935,1003,978,1116,951,909,723,462,176,3
3,4,2024-01-01,1호선,151,시청,하차,103,276,292,451,...,834,697,670,564,351,302,272,120,89,38
4,5,2024-01-01,1호선,152,종각,승차,970,374,193,205,...,1383,1578,1435,1422,1287,1318,1106,775,274,8

In [18]:
subway2024.isnull().sum()

연번         0
날짜         0
호선         0
역번호        0
역명         0
구분         0
06시 이전     0
06시-07시    0
07시-08시    0
08시-09시    0
09시-10시    0
10시-11시    0
11시-12시    0
12시-13시    0
13시-14시    0
14시-15시    0
15시-16시    0
16시-17시    0
17시-18시    0
18시-19시    0
19시-20시    0
20시-21시    0
21시-22시    0
22시-23시    0
23시-24시    0
24시 이후     0
dtype: int64

In [19]:
subway2024 = subway2024.rename(columns={
    '날짜': '수송일자',
    '구분': '승하차구분',
    '06시 이전': '06시이전',
    '06시-07시': '06-07시간대',
    '07시-08시': '07-08시간대',
    '08시-09시': '08-09시간대',
    '09시-10시': '09-10시간대',
    '10시-11시': '10-11시간대',
    '11시-12시': '11-12시간대',
    '12시-13시': '12-13시간대',
    '13시-14시': '13-14시간대',
    '14시-15시': '14-15시간대',
    '15시-16시': '15-16시간대',
    '16시-17시': '16-17시간대',
    '17시-18시': '17-18시간대',
    '18시-19시': '18-19시간대',
    '19시-20시': '19-20시간대',
    '20시-21시': '20-21시간대',
    '21시-22시': '21-22시간대',
    '22시-23시': '22-23시간대',
    '23시-24시': '23-24시간대',
    '24시 이후': '24시이후'
})

In [20]:
subway2024.head()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,1,2024-01-01,1호선,150,서울역,승차,383,257,308,975,...,2716,2882,2871,2685,2922,2031,2279,1729,868,43
1,2,2024-01-01,1호선,150,서울역,하차,249,867,834,1201,...,2615,2501,2829,2095,1833,1465,1031,585,298,82
2,3,2024-01-01,1호선,151,시청,승차,188,92,167,245,...,935,1003,978,1116,951,909,723,462,176,3
3,4,2024-01-01,1호선,151,시청,하차,103,276,292,451,...,834,697,670,564,351,302,272,120,89,38
4,5,2024-01-01,1호선,152,종각,승차,970,374,193,205,...,1383,1578,1435,1422,1287,1318,1106,775,274,8

#학습 데이터 만들기

In [21]:
#데이터 합치기
subway_data = pd.concat([subway2022, subway2023, subway2024], axis=0)

In [22]:
subway_data.head()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,1,2022-01-01,1,150,서울역,승차,120,137,211,439,...,1566,1686,1591,1358,1062,899,1327,814,234,NaN
1,2,2022-01-01,1,150,서울역,하차,113,560,617,910,...,1329,1251,1126,884,764,654,728,416,131,NaN
2,3,2022-01-01,1,151,시청,승차,38,66,101,139,...,474,550,672,528,420,434,491,232,38,NaN
3,4,2022-01-01,1,151,시청,하차,31,195,224,380,...,408,377,354,213,131,98,137,61,24,NaN
4,5,2022-01-01,1,152,종각,승차,44,71,86,158,...,889,964,1024,803,855,1099,1209,255,62,NaN

In [23]:
subway_data.tail()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
199405,199406,2024-12-31,8호선,2826,수진,하차,14,85,152,477,...,355,414,465,468,376,261,248,246,175,68.0
199406,199407,2024-12-31,8호선,2827,모란,승차,80,103,332,400,...,389,537,440,381,247,136,170,140,90,50.0
199407,199408,2024-12-31,8호선,2827,모란,하차,19,109,138,428,...,263,340,340,374,281,193,212,207,141,128.0
199408,199409,2024-12-31,8호선,2828,남위례,승차,44,236,686,811,...,656,469,556,513,285,245,216,213,75,46.0
199409,199410,2024-12-31,8호선,2828,남위례,하차,40,138,306,913,...,377,569,664,781,551,342,276,256,148,69.0

In [24]:
# 이태원 승차 데이터 분리
itaewon_get_off = subway_data[(subway_data['역명'] == '이태원') & (subway_data['승하차구분'] == '하차')]

In [25]:
itaewon_get_off.head()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
389,390,2022-01-01,6,2631,이태원,하차,28,92,72,134,...,779,1047,1112,946,482,277,302,188,91,NaN
933,934,2022-01-02,6,2631,이태원,하차,27,93,118,135,...,652,769,761,571,308,199,263,146,82,NaN
1477,1478,2022-01-03,6,2631,이태원,하차,31,211,443,982,...,388,563,615,768,514,261,278,155,80,NaN
2023,2024,2022-01-04,6,2631,이태원,하차,29,209,459,980,...,438,594,654,801,489,263,316,173,79,NaN
2571,2572,2022-01-05,6,2631,이태원,하차,29,215,452,966,...,446,602,684,924,543,268,311,180,112,NaN

In [26]:
itaewon_get_off.tail()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
197069,197070,2024-12-27,6호선,2631,이태원,하차,63,421,403,1017,...,700,919,1239,1640,1505,1096,1012,1060,871,492.0
197615,197616,2024-12-28,6호선,2631,이태원,하차,55,322,184,236,...,902,1288,1552,1684,1580,1581,1423,1490,1258,242.0
198161,198162,2024-12-29,6호선,2631,이태원,하차,61,170,125,161,...,752,944,1029,821,748,541,433,456,370,63.0
198707,198708,2024-12-30,6호선,2631,이태원,하차,46,330,414,947,...,647,756,957,1125,736,516,486,388,320,109.0
199253,199254,2024-12-31,6호선,2631,이태원,하차,33,278,371,894,...,725,937,1210,1511,1591,1730,1887,2267,1900,816.0

In [27]:
itaewon_get_off['승하차구분'].unique()

array(['하차'], dtype=object)

2022년 1월 ~ 2022년 5월까지는 24시 이후 데이터가 null이므로 2022년 6월 데이터부터 활용

In [28]:
#2022년 5월 31일이 어디까지인지 확인
np.where(itaewon_get_off['수송일자'] == '2022-05-31')

(array([150]),)

In [29]:
#2022년 5월 31일이 어디까지인지 확인
np.where(itaewon_get_off['수송일자'] == '2022-06-01')

(array([151]),)

In [30]:
itaewon_get_off = itaewon_get_off[151:]

In [31]:
itaewon_get_off.head()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
82737,82738,2022-06-01,6,2631,이태원,하차,72,192,181,238,...,847,913,999,895,630,579,468,313,239,24.0
83281,83282,2022-06-02,6,2631,이태원,하차,40,239,430,1314,...,485,685,858,1377,1037,601,395,444,286,55.0
83827,83828,2022-06-03,6,2631,이태원,하차,39,246,463,1202,...,619,804,1051,1871,1852,1379,1179,1054,998,176.0
84373,84374,2022-06-04,6,2631,이태원,하차,51,183,175,306,...,1141,1475,1738,2000,1901,1798,1654,1367,1248,248.0
84919,84920,2022-06-05,6,2631,이태원,하차,69,153,133,182,...,1065,1135,1410,1488,1304,1142,1034,704,742,181.0

## Prophet에 활용할 수 있는 형태로 데이터 바꾸기(ds, y 형태)

In [32]:
#시간대 별로 예측을 진행해야 하므로 시간대를 열 -> 행으로 변경

id_vars =['수송일자', '호선', '역번호', '역명', '승하차구분']
value_vars = ['06시이전', '06-07시간대',
    '07-08시간대', '08-09시간대', '09-10시간대', '10-11시간대', '11-12시간대', '12-13시간대',
    '13-14시간대', '14-15시간대', '15-16시간대', '16-17시간대', '17-18시간대', '18-19시간대',
    '19-20시간대', '20-21시간대', '21-22시간대', '22-23시간대', '23-24시간대', '24시이후']

itaewon_get_off_melt = pd.melt(itaewon_get_off,
                            id_vars=id_vars,
                            value_vars=value_vars,
                            var_name='시간대',
                            value_name='이용객수')

In [33]:
itaewon_get_off_melt.head()

         수송일자 호선   역번호   역명 승하차구분    시간대  이용객수
0  2022-06-01  6  2631  이태원    하차  06시이전  72.0
1  2022-06-02  6  2631  이태원    하차  06시이전  40.0
2  2022-06-03  6  2631  이태원    하차  06시이전  39.0
3  2022-06-04  6  2631  이태원    하차  06시이전  51.0
4  2022-06-05  6  2631  이태원    하차  06시이전  69.0

In [34]:
itaewon_get_off_melt.tail()

             수송일자   호선   역번호   역명 승하차구분    시간대   이용객수
18895  2024-12-27  6호선  2631  이태원    하차  24시이후  492.0
18896  2024-12-28  6호선  2631  이태원    하차  24시이후  242.0
18897  2024-12-29  6호선  2631  이태원    하차  24시이후   63.0
18898  2024-12-30  6호선  2631  이태원    하차  24시이후  109.0
18899  2024-12-31  6호선  2631  이태원    하차  24시이후  816.0

In [35]:
itaewon_get_off_melt[itaewon_get_off_melt['수송일자'] == '2023-02-04']

             수송일자   호선   역번호   역명 승하차구분       시간대    이용객수
248    2023-02-04  6호선  2631  이태원    하차     06시이전    38.0
1193   2023-02-04  6호선  2631  이태원    하차  06-07시간대   193.0
2138   2023-02-04  6호선  2631  이태원    하차  07-08시간대   204.0
3083   2023-02-04  6호선  2631  이태원    하차  08-09시간대   255.0
4028   2023-02-04  6호선  2631  이태원    하차  09-10시간대   337.0
4973   2023-02-04  6호선  2631  이태원    하차  10-11시간대   542.0
5918   2023-02-04  6호선  2631  이태원    하차  11-12시간대   672.0
6863   2023-02-04  6호선  2631  이태원    하차  12-13시간대   845.0
7808   2023-02-04  6호선  2631  이태원    하차  13-14시간대  1044.0
8753   2023-02-04  6호선  2631  이태원    하차  14-15시간대  1033.0
9698   2023-02-04  6호선  2631  이태원    하차  15-16시간대  1106.0
10643  2023-02-04  6호선  2631  이태원    하차  16-17시간대  1152.0
11588  2023-02-04  6호선  2631  이태원    하차  17-18시간대  1215.0
12533  2023-02-04  6호선  2631  이태원    하차  18-19시간대  1206.0
13478  2023-02-04  6호선  2631  이태원    하차  19-20시간대   985.0
14423  2023-02-04  6호선  2631  이태원    하차  20-21시간대   802.0
15368  2023-02-04  6호선  2631  이태원    하차  21-22시간대   665.0
16313  2023-02-04  6호선  2631  이태원    하차  22-23시간대   587.0
17258  2023-02-04  6호선  2631  이태원    하차  23-24시간대   600.0
18203  2023-02-04  6호선  2631  이태원    하차     24시이후   128.0

In [36]:
itaewon_get_off_melt.isnull().sum()

수송일자     0
호선       0
역번호      0
역명       0
승하차구분    0
시간대      0
이용객수     0
dtype: int64

In [37]:
#6시 이전: 첫차 5시 30분대 (토요일 및 공휴일 동일)
#24시 이후: 막차 12시 48분 (평일) / 23시 59분(토요일 및 공휴일)
def get_ds(row):
    date = pd.to_datetime(row['수송일자'])
    t = row['시간대']
    if '이전' in t: #6시 이전 -> 첫차 5:30분대
        time_str = '05:00:00'
    elif '이후' in t: #12시 이후 -> 막차
        date += pd.Timedelta(days=1)  # 다음 날로 이동
        time_str = '00:00:00'
    else:
        hour = int(t[:2])
        time_str = f'{hour:02d}:00:00'

    return pd.to_datetime(f"{date.date()} {time_str}")

In [38]:
itaewon_get_off_melt['ds'] = itaewon_get_off_melt.apply(get_ds, axis=1)

In [39]:
itaewon_get_off_melt.head()

         수송일자 호선   역번호   역명 승하차구분    시간대  이용객수                  ds
0  2022-06-01  6  2631  이태원    하차  06시이전  72.0 2022-06-01 05:00:00
1  2022-06-02  6  2631  이태원    하차  06시이전  40.0 2022-06-02 05:00:00
2  2022-06-03  6  2631  이태원    하차  06시이전  39.0 2022-06-03 05:00:00
3  2022-06-04  6  2631  이태원    하차  06시이전  51.0 2022-06-04 05:00:00
4  2022-06-05  6  2631  이태원    하차  06시이전  69.0 2022-06-05 05:00:00

In [40]:
itaewon_get_off_melt.tail()

             수송일자   호선   역번호   역명 승하차구분    시간대   이용객수         ds
18895  2024-12-27  6호선  2631  이태원    하차  24시이후  492.0 2024-12-28
18896  2024-12-28  6호선  2631  이태원    하차  24시이후  242.0 2024-12-29
18897  2024-12-29  6호선  2631  이태원    하차  24시이후   63.0 2024-12-30
18898  2024-12-30  6호선  2631  이태원    하차  24시이후  109.0 2024-12-31
18899  2024-12-31  6호선  2631  이태원    하차  24시이후  816.0 2025-01-01

In [41]:
#00시(24시) 맞게 표현되었는지 다시 확인
itaewon_get_off_melt[itaewon_get_off_melt["ds"].dt.hour == 0]

             수송일자   호선   역번호   역명 승하차구분    시간대   이용객수         ds
17955  2022-06-01    6  2631  이태원    하차  24시이후   24.0 2022-06-02
17956  2022-06-02    6  2631  이태원    하차  24시이후   55.0 2022-06-03
17957  2022-06-03    6  2631  이태원    하차  24시이후  176.0 2022-06-04
17958  2022-06-04    6  2631  이태원    하차  24시이후  248.0 2022-06-05
17959  2022-06-05    6  2631  이태원    하차  24시이후  181.0 2022-06-06
...           ...  ...   ...  ...   ...    ...    ...        ...
18895  2024-12-27  6호선  2631  이태원    하차  24시이후  492.0 2024-12-28
18896  2024-12-28  6호선  2631  이태원    하차  24시이후  242.0 2024-12-29
18897  2024-12-29  6호선  2631  이태원    하차  24시이후   63.0 2024-12-30
18898  2024-12-30  6호선  2631  이태원    하차  24시이후  109.0 2024-12-31
18899  2024-12-31  6호선  2631  이태원    하차  24시이후  816.0 2025-01-01

[945 rows x 8 columns]

In [42]:
itaewon_get_off_melt['승하차구분'].unique()

array(['하차'], dtype=object)

In [43]:
itaewon_get_off_melt = itaewon_get_off_melt.rename(columns={
    '이용객수': 'y'
})

In [44]:
df_prophet = itaewon_get_off_melt[['ds', 'y']].copy()

In [45]:
#변수로 활용할 시간, 요일, 달, 주말 여부, 할로윈 여부 추가
df_prophet['hour'] = df_prophet['ds'].dt.hour #시간
df_prophet['dayofweek'] = df_prophet['ds'].dt.day_of_week #요일
df_prophet['month'] = df_prophet['ds'].dt.month #월
df_prophet['is_weekend'] = df_prophet['ds'].dt.dayofweek.isin([5, 6]).astype(int) #주말여부(주말의 경우 막차가 24시 이전에 끊김)
df_prophet['is_halloween'] = df_prophet['ds'].apply(lambda x: 1 if x.month == 10 and x.day == 31 else 0) #할로윈 여부

In [46]:
df_prophet

,ds,y,hour,dayofweek,month,is_weekend,is_halloween
0,2022-06-01 05:00:00,72.0,5,2,6,0,0
1,2022-06-02 05:00:00,40.0,5,3,6,0,0
2,2022-06-03 05:00:00,39.0,5,4,6,0,0
3,2022-06-04 05:00:00,51.0,5,5,6,1,0
4,2022-06-05 05:00:00,69.0,5,6,6,1,0
...,...,...,...,...,...,...,...
18895,2024-12-28 00:00:00,492.0,0,5,12,1,0
18896,2024-12-29 00:00:00,242.0,0,6,12,1,0
18897,2024-12-30 00:00:00,63.0,0,0,12,0,0
18898,2024-12-31 00:00:00,109.0,0,1,12,0,0
18899,2025-01-01 00:00:00,816.0,0,2,1,0,0

In [47]:
#요일, 달, 시간에 대해 원핫 인코딩 진행
df_prophet = pd.get_dummies(df_prophet, columns=['dayofweek', 'month', 'hour'], dtype=int)

In [48]:
df_prophet.head()

,ds,y,is_weekend,is_halloween,dayofweek_0,dayofweek_1,dayofweek_2,dayofweek_3,dayofweek_4,dayofweek_5,...,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23
0,2022-06-01 05:00:00,72.0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2022-06-02 05:00:00,40.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2022-06-03 05:00:00,39.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2022-06-04 05:00:00,51.0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2022-06-05 05:00:00,69.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [49]:
df_prophet.columns

Index(['ds', 'y', 'is_weekend', 'is_halloween', 'dayofweek_0', 'dayofweek_1',
       'dayofweek_2', 'dayofweek_3', 'dayofweek_4', 'dayofweek_5',
       'dayofweek_6', 'month_1', 'month_2', 'month_3', 'month_4', 'month_5',
       'month_6', 'month_7', 'month_8', 'month_9', 'month_10', 'month_11',
       'month_12', 'hour_0', 'hour_5', 'hour_6', 'hour_7', 'hour_8', 'hour_9',
       'hour_10', 'hour_11', 'hour_12', 'hour_13', 'hour_14', 'hour_15',
       'hour_16', 'hour_17', 'hour_18', 'hour_19', 'hour_20', 'hour_21',
       'hour_22', 'hour_23'],
      dtype='object')

#모델 생성 및 정의

In [50]:
from prophet import Prophet

# Prophet 모델 생성 및 학습
#dail, weekly 패턴 학습하도록 설정(지하철 특성 반영)
model = Prophet(
    daily_seasonality=True,
    weekly_seasonality=True,
    changepoint_prior_scale=0.1
)

In [51]:
#외생변수 추가
for col in df_prophet.columns:
    if col.startswith('month_') or col.startswith('dayofweek_') or col.startswith('hour_'):
        model.add_regressor(col)
model.add_regressor('is_weekend')
model.add_regressor('is_halloween')
# 한국 공휴일 추가
model.add_country_holidays(country_name='KR')

#모델 훈련(사용 데이터 2022년 6월 1일 ~ 2024년 12월 31일)

In [52]:
#모델 학습
model.fit(df_prophet)

#모델 평가(사용 데이터 2025년 1월 1일 ~ 2025년 12월 31일)

##데이터 전처리

In [53]:
subway_2025 = pd.read_csv("/content/서울교통공사_역별 일별 시간대별 승하차인원_20251231.csv", encoding='cp949')

In [54]:
itaewon_2025 = subway_2025[(subway_2025['역명'] == '이태원') & (subway_2025['승하차구분'] == '하차')]

In [55]:
itaewon_2025['승하차구분'].unique()

array(['하차'], dtype=object)

In [56]:
itaewon_2025_melt = pd.melt(itaewon_2025,
                            id_vars=id_vars,
                            value_vars=value_vars,
                            var_name='시간대',
                            value_name='이용객수')

In [57]:
itaewon_2025_melt.head()

         수송일자   호선     역번호   역명 승하차구분    시간대   이용객수
0  2025-01-01  6호선  2631.0  이태원    하차  06시이전  106.0
1  2025-01-02  6호선  2631.0  이태원    하차  06시이전   52.0
2  2025-01-03  6호선  2631.0  이태원    하차  06시이전   61.0
3  2025-01-04  6호선  2631.0  이태원    하차  06시이전   58.0
4  2025-01-05  6호선  2631.0  이태원    하차  06시이전   42.0

In [58]:
itaewon_2025_melt.isnull().sum()

수송일자     0
호선       0
역번호      0
역명       0
승하차구분    0
시간대      0
이용객수     0
dtype: int64

In [59]:
itaewon_2025_melt['ds'] = itaewon_2025_melt.apply(get_ds, axis=1)

In [60]:
itaewon_2025_melt = itaewon_2025_melt.rename(columns={
    '이용객수': 'y'
})

In [61]:
itaewon_2025_melt['승하차구분'].unique()

array(['하차'], dtype=object)

In [62]:
itaewon_2025_melt.head()

         수송일자   호선     역번호   역명 승하차구분    시간대      y                  ds
0  2025-01-01  6호선  2631.0  이태원    하차  06시이전  106.0 2025-01-01 05:00:00
1  2025-01-02  6호선  2631.0  이태원    하차  06시이전   52.0 2025-01-02 05:00:00
2  2025-01-03  6호선  2631.0  이태원    하차  06시이전   61.0 2025-01-03 05:00:00
3  2025-01-04  6호선  2631.0  이태원    하차  06시이전   58.0 2025-01-04 05:00:00
4  2025-01-05  6호선  2631.0  이태원    하차  06시이전   42.0 2025-01-05 05:00:00

In [63]:
itaewon_2025_melt.tail()

            수송일자   호선     역번호   역명 승하차구분    시간대       y         ds
7295  2025-12-27  6호선  2631.0  이태원    하차  24시이후   267.0 2025-12-28
7296  2025-12-28  6호선  2631.0  이태원    하차  24시이후   125.0 2025-12-29
7297  2025-12-29  6호선  2631.0  이태원    하차  24시이후   144.0 2025-12-30
7298  2025-12-30  6호선  2631.0  이태원    하차  24시이후   151.0 2025-12-31
7299  2025-12-31  6호선  2631.0  이태원    하차  24시이후  1450.0 2026-01-01

In [64]:
df_prophet_2025 = itaewon_2025_melt[['ds', 'y']].copy()

In [65]:
df_prophet_2025['hour'] = df_prophet_2025['ds'].dt.hour #시간
df_prophet_2025['dayofweek'] = df_prophet_2025['ds'].dt.day_of_week #요일
df_prophet_2025['month'] = df_prophet_2025['ds'].dt.month #월
df_prophet_2025['is_weekend'] = df_prophet_2025['ds'].dt.dayofweek.isin([5, 6]).astype(int) #주말여부
df_prophet_2025['is_halloween'] = df_prophet_2025['ds'].apply(lambda x: 1 if x.month == 10 and x.day == 31 else 0) #할로윈 여부

In [66]:
df_prophet_2025 = pd.get_dummies(df_prophet_2025, columns=['dayofweek', 'month', 'hour'], dtype=int)

In [67]:
df_prophet_2025.columns

Index(['ds', 'y', 'is_weekend', 'is_halloween', 'dayofweek_0', 'dayofweek_1',
       'dayofweek_2', 'dayofweek_3', 'dayofweek_4', 'dayofweek_5',
       'dayofweek_6', 'month_1', 'month_2', 'month_3', 'month_4', 'month_5',
       'month_6', 'month_7', 'month_8', 'month_9', 'month_10', 'month_11',
       'month_12', 'hour_0', 'hour_5', 'hour_6', 'hour_7', 'hour_8', 'hour_9',
       'hour_10', 'hour_11', 'hour_12', 'hour_13', 'hour_14', 'hour_15',
       'hour_16', 'hour_17', 'hour_18', 'hour_19', 'hour_20', 'hour_21',
       'hour_22', 'hour_23'],
      dtype='object')

In [68]:
df_prophet_2025.head()

,ds,y,is_weekend,is_halloween,dayofweek_0,dayofweek_1,dayofweek_2,dayofweek_3,dayofweek_4,dayofweek_5,...,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23
0,2025-01-01 05:00:00,106.0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2025-01-02 05:00:00,52.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2025-01-03 05:00:00,61.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2025-01-04 05:00:00,58.0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2025-01-05 05:00:00,42.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

###예측에 사용할 데이터 프레임 만들기(y-승객수 drop)

In [69]:
#y(승객수) drop
future = df_prophet_2025.drop(columns='y')

In [70]:
future.columns

Index(['ds', 'is_weekend', 'is_halloween', 'dayofweek_0', 'dayofweek_1',
       'dayofweek_2', 'dayofweek_3', 'dayofweek_4', 'dayofweek_5',
       'dayofweek_6', 'month_1', 'month_2', 'month_3', 'month_4', 'month_5',
       'month_6', 'month_7', 'month_8', 'month_9', 'month_10', 'month_11',
       'month_12', 'hour_0', 'hour_5', 'hour_6', 'hour_7', 'hour_8', 'hour_9',
       'hour_10', 'hour_11', 'hour_12', 'hour_13', 'hour_14', 'hour_15',
       'hour_16', 'hour_17', 'hour_18', 'hour_19', 'hour_20', 'hour_21',
       'hour_22', 'hour_23'],
      dtype='object')

In [71]:
future.head()

,ds,is_weekend,is_halloween,dayofweek_0,dayofweek_1,dayofweek_2,dayofweek_3,dayofweek_4,dayofweek_5,dayofweek_6,...,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23
0,2025-01-01 05:00:00,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2025-01-02 05:00:00,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2025-01-03 05:00:00,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2025-01-04 05:00:00,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2025-01-05 05:00:00,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

##모델 예측

In [72]:
#모델 예측
forecast = model.predict(future)

In [73]:
forecast.columns

Index(['ds', 'trend', 'yhat_lower', 'yhat_upper', 'trend_lower', 'trend_upper',
       'Alternative holiday for Buddha's Birthday',
       'Alternative holiday for Buddha's Birthday_lower',
       'Alternative holiday for Buddha's Birthday_upper',
       'Alternative holiday for Children's Day',
       ...
       'weekly', 'weekly_lower', 'weekly_upper', 'yearly', 'yearly_lower',
       'yearly_upper', 'multiplicative_terms', 'multiplicative_terms_lower',
       'multiplicative_terms_upper', 'yhat'],
      dtype='object', length=229)

##모델 평가

In [74]:
forecast.head()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,Alternative holiday for Buddha's Birthday,Alternative holiday for Buddha's Birthday_lower,Alternative holiday for Buddha's Birthday_upper,Alternative holiday for Children's Day,...,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2025-01-01 05:00:00,604.654015,-205.078504,465.302713,604.654015,604.654015,0.0,0.0,0.0,0.0,...,-163.962839,-163.962839,-163.962839,110.923605,110.923605,110.923605,0.0,0.0,0.0,134.722100
1,2025-01-01 06:00:00,604.674429,-5.465768,671.973171,604.674429,604.674429,0.0,0.0,0.0,0.0,...,-181.356084,-181.356084,-181.356084,110.957295,110.957295,110.957295,0.0,0.0,0.0,344.827427
2,2025-01-01 07:00:00,604.694843,85.194276,794.920566,604.694843,604.694843,0.0,0.0,0.0,0.0,...,-198.692851,-198.692851,-198.692851,110.990960,110.990960,110.990960,0.0,0.0,0.0,442.593900
3,2025-01-01 08:00:00,604.715257,616.600516,1301.007941,604.715257,604.715257,0.0,0.0,0.0,0.0,...,-215.952003,-215.952003,-215.952003,111.024602,111.024602,111.024602,0.0,0.0,0.0,960.491415
4,2025-01-01 09:00:00,604.735671,484.082955,1187.395838,604.735671,604.735671,0.0,0.0,0.0,0.0,...,-233.113839,-233.113839,-233.113839,111.058221,111.058221,111.058221,0.0,0.0,0.0,831.316058

In [75]:
forecast.tail()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,Alternative holiday for Buddha's Birthday,Alternative holiday for Buddha's Birthday_lower,Alternative holiday for Buddha's Birthday_upper,Alternative holiday for Children's Day,...,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
7295,2025-12-31 20:00:00,783.296734,-836.419258,2384.788879,-846.101729,2317.002164,0.0,0.0,0.0,0.0,...,-411.970132,-411.970132,-411.970132,110.414900,110.414900,110.414900,0.0,0.0,0.0,824.432436
7296,2025-12-31 21:00:00,783.317148,-948.467801,2373.532569,-846.487704,2317.343808,0.0,0.0,0.0,0.0,...,-427.225430,-427.225430,-427.225430,110.449035,110.449035,110.449035,0.0,0.0,0.0,719.564843
7297,2025-12-31 22:00:00,783.337562,-1050.678309,2212.695477,-846.873678,2317.685452,0.0,0.0,0.0,0.0,...,-442.328520,-442.328520,-442.328520,110.483135,110.483135,110.483135,0.0,0.0,0.0,649.373600
7298,2025-12-31 23:00:00,783.357976,-1140.574630,2061.189372,-847.259653,2318.027097,0.0,0.0,0.0,0.0,...,-457.287771,-457.287771,-457.287771,110.517200,110.517200,110.517200,0.0,0.0,0.0,519.230944
7299,2026-01-01 00:00:00,783.378390,-1179.969724,2098.911493,-847.645627,2318.368741,0.0,0.0,0.0,0.0,...,-472.111770,-472.111770,-472.111770,110.551232,110.551232,110.551232,0.0,0.0,0.0,510.738564

In [76]:
df_prophet_2025.head()

,ds,y,is_weekend,is_halloween,dayofweek_0,dayofweek_1,dayofweek_2,dayofweek_3,dayofweek_4,dayofweek_5,...,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23
0,2025-01-01 05:00:00,106.0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2025-01-02 05:00:00,52.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2025-01-03 05:00:00,61.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2025-01-04 05:00:00,58.0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2025-01-05 05:00:00,42.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
df_prophet_2025.tail()

,ds,y,is_weekend,is_halloween,dayofweek_0,dayofweek_1,dayofweek_2,dayofweek_3,dayofweek_4,dayofweek_5,...,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23
7295,2025-12-28,267.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7296,2025-12-29,125.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7297,2025-12-30,144.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7298,2025-12-31,151.0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7299,2026-01-01,1450.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
#forecast의 yhat(예측값)과 df_prophet_2025의 y(실제값)을 ds를 기준으로 하나의 데이터 프레임으로 만들기
result = df_prophet_2025[['ds', 'y']].merge(forecast[['ds', 'yhat']],on='ds')
result

                      ds       y        yhat
0    2025-01-01 05:00:00   106.0  134.722100
1    2025-01-02 05:00:00    52.0  144.346759
2    2025-01-03 05:00:00    61.0  139.776212
3    2025-01-04 05:00:00    58.0  -44.606885
4    2025-01-05 05:00:00    42.0  -83.275604
...                  ...     ...         ...
7295 2025-12-28 00:00:00   267.0  133.174334
7296 2025-12-29 00:00:00   125.0  573.139396
7297 2025-12-30 00:00:00   144.0  559.020498
7298 2025-12-31 00:00:00   151.0  591.632862
7299 2026-01-01 00:00:00  1450.0  510.738564

[7300 rows x 3 columns]

In [79]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(result['y'], result['yhat'])
rmse = np.sqrt(mean_squared_error(result['y'], result['yhat']))

print(f"MAE : {mae:.3f}")
print(f"RMSE: {rmse:.3f}")

MAE : 228.256
RMSE: 283.611

#모델 저장

In [80]:
import joblib
joblib.dump(model, 'get_off_model.pkl')

['get_off_model.pkl']